sudo: false
language: node_js
node_js:
  - node
  - lts/*
  - 10
# branches:
#   only:
#     - master
cache:
  yarn: true
  directories:
    - node_modules
before_install:
  - yarn update
install:
  - yarn install
script:
  - yarn coveralls
